server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service
  profiles:
    active: default,monitoring
  datasource:
    url: jdbc:postgresql://localhost:5432/clinic_salon_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
    show-sql: false
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

# JWT Configuration
clinica-salon:
  security:
    jwt:
      token:
        secret-key: ${JWT_SECRET:defaultsecretkeymustbelongerthan256bits}
        expire-length: 3600000 # 1 hour in milliseconds

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    root: INFO
    '[org.springframework.web]': INFO
    '[org.springframework.security]': INFO
    '[com.clinicsalon.auth]': DEBUG
