{
 "title": "Clinica Salão - Monitoramento de Microserviços",
 "tags": [
  "clinica-salao",
  "microservices"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tempo de Execução de Métodos - Auth Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "method_execution_time_seconds_max{application=\"auth-service\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Tempo de Execução de Métodos - Professional Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "method_execution_time_seconds_max{application=\"professional-service\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Cache Hits - Auth Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cache_gets_total{application=\"auth-service\"} - cache_misses_total{application=\"auth-service\"}",
     "legendFormat": "{{cache}} - Hits"
    }
   ]
  },
  {
   "title": "Cache Misses - Auth Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cache_misses_total{application=\"auth-service\"}",
     "legendFormat": "{{cache}} - Misses"
    }
   ]
  },
  {
   "title": "Estado do Circuit Breaker - Loyalty Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{application=\"loyalty-service\", state=\"closed\"} == 1",
     "legendFormat": "{{name}} - Closed"
    },
    {
     "expr": "resilience4j_circuitbreaker_state{application=\"loyalty-service\", state=\"open\"} == 1",
     "legendFormat": "{{name}} - Open"
    },
    {
     "expr": "resilience4j_circuitbreaker_state{application=\"loyalty-service\", state=\"half_open\"} == 1",
     "legendFormat": "{{name}} - Half Open"
    }
   ]
  },
  {
   "title": "Tempo de Execução de Métodos - Report Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "method_execution_time_seconds_max{application=\"report-service\"}",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}