server:
  port: 8083

spring:
  application:
    name: professional-service
  profiles:
    active: default,monitoring
  
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/clinicsalon_professional
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
  
  flyway:
    enabled: true
    baseline-on-migrate: true

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# Springdoc OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
