server:
  port: 8084

spring:
  application:
    name: appointment-service
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:h2:mem:appointment_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: false
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

resilience4j:
  circuitbreaker:
    instances:
      clientService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
      professionalService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
      financeService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
      loyaltyService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
      notificationService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
  retry:
    instances:
      clientService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
      professionalService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
      financeService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
      loyaltyService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
      notificationService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  bulkhead:
    instances:
      clientService:
        maxConcurrentCalls: 10
        maxWaitDuration: 10ms
      professionalService:
        maxConcurrentCalls: 10
        maxWaitDuration: 10ms
      financeService:
        maxConcurrentCalls: 10
        maxWaitDuration: 10ms
      loyaltyService:
        maxConcurrentCalls: 10
        maxWaitDuration: 10ms
      notificationService:
        maxConcurrentCalls: 20
        maxWaitDuration: 10ms
